name: Grant Access
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  grant-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'SDM Access'
        uses: actions/sdm-access-gh-action@v2
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RUN_ID: ${{ github.run_id }}
          ACTOR_NAME: ${{ github.actor }}
