name: Grant Access
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  grant-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t access-granter < ./Dockerfile

      - name: 'SDM Access'
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RUN_ID: ${{ github.run_id }}
          ACTOR_NAME: ${{ github.actor }}
        run: docker run access-granter
