name: Grant Access
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  grant-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: 'SDM Access Granter Client'
        uses: ./
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          RUN_ID: ${{ github.run_id }}
          ACTOR_NAME: ${{ github.actor }}
